Repository geosolutions-it/geostore, pull requests merged in 2024-10, with the labels that each got.

#366 Fix modules
  src/pom.xml
Labels: Backport Needed

#370 #369 Clean up maven profiles
  .github/workflows/CI.yml
  .github/workflows/release.yml
  .travis.yml
  README.md
  run4MS.sh
  src/cli/README.md
  src/pom.xml
  src/web/app/pom.xml
Labels: Internal

#374 [Backport 2.2.x][FIXES #2408] C206-DEUTSCHE_BAHN-2023-SUPPORT - SSO - Supported OpenI…
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/GeoStoreKeycloakAuthProvider.java
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakFilter.java
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2Configuration.java
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2GeoStoreAuthenticationFilter.java
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2GeoStoreSecurityConfiguration.java
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2SessionServiceDelegate.java
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/openid_connect/OpenIdConnectFilter.java
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/openid_connect/OpenIdConnectSecurityConfiguration.java
  src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/oauth2/openid_connect/OpenIdConnectIntegrationTest.java
Labels: C206-DEUTSCHE_BAHN-2023-SUPPORT, backport

#375 [Backport 2.2.x] The "saferJWT" method should be called only when logging. It should n…
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/GeoStoreOAuthRestTemplate.java
Labels: C206-DEUTSCHE_BAHN-2023-SUPPORT, backport

#376 Update mockito version to 4.0.0
  src/pom.xml
Labels: enhancement, Internal

#377 [Backport] Update mockito version to 4.0.0
  src/pom.xml
Labels: enhancement, Internal
