Repository geosolutions-it/geostore, pull requests merged in 2024-03, with the labels that each got.

#340 Dependency updates
  pom.xml
  src/cli/pom.xml
  src/core/model/pom.xml
  src/core/persistence/pom.xml
  src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/UserGroupDAOImpl.java
  src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ldap/UserDAOTest.java
  src/core/security/pom.xml
  src/core/security/src/main/java/it/geosolutions/geostore/core/security/JSONExpressionUserMapper.java
  src/core/security/src/main/java/it/geosolutions/geostore/core/security/password/GeoStoreDigestPasswordEncoder.java
  src/core/security/src/main/java/it/geosolutions/geostore/core/security/password/GeoStorePBEPasswordEncoder.java
  src/core/services-api/pom.xml
  src/core/services-impl/pom.xml
  src/modules/rest/api/pom.xml
  src/modules/rest/auditing/pom.xml
  src/modules/rest/client/pom.xml
  src/modules/rest/extjs/pom.xml
  src/modules/rest/impl/pom.xml
  src/modules/rest/test/pom.xml
  src/pom.xml
  src/web/app/pom.xml
Labels: dependencies, C125-AUSTROCONTROL-2023-MapStore

#345 Fix #344. Remove NVD check by default
  pom.xml
Labels: backportNeeded

#343 [Backport 2.1.x] Dependency updates and NVD skip (#340) (#345)
  pom.xml
  src/cli/pom.xml
  src/core/model/pom.xml
  src/core/persistence/pom.xml
  src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/UserGroupDAOImpl.java
  src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ldap/UserDAOTest.java
  src/core/security/pom.xml
  src/core/security/src/main/java/it/geosolutions/geostore/core/security/JSONExpressionUserMapper.java
  src/core/security/src/main/java/it/geosolutions/geostore/core/security/password/GeoStoreDigestPasswordEncoder.java
  src/core/security/src/main/java/it/geosolutions/geostore/core/security/password/GeoStorePBEPasswordEncoder.java
  src/core/services-api/pom.xml
  src/core/services-impl/pom.xml
  src/modules/rest/api/pom.xml
  src/modules/rest/auditing/pom.xml
  src/modules/rest/client/pom.xml
  src/modules/rest/extjs/pom.xml
  src/modules/rest/impl/pom.xml
  src/modules/rest/test/pom.xml
  src/pom.xml
  src/web/app/pom.xml
Labels: backport
