Repository geosolutions-it/geostore, pull requests merged in 2024-11, with the labels that each got.

#385 Improvements with OKTA OIDC provider integration
  src/modules/rest/impl/pom.xml
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTSessionServiceImpl.java
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2SessionServiceDelegate.java
  src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/oauth2/openid_connect/RefreshTokenServiceTest.java
Labels: C039-2024-HALLIBURTON-SUPPORT

#387 Bump org.springframework.security:spring-security-web from 5.7.12 to 5.7.13 in /src
  src/pom.xml
Labels: Internal, dependencies

#390 Update mvn compiler plugin in root pom.xml to run with java 11
  pom.xml
Labels: Internal
