Repository geosolutions-it/geostore, pull requests merged in 2025-05, with the labels that each got.

#427 Improved logging on authentication
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/UserServiceAuthenticationProvider.java
Labels: Backport Needed

#430 Backporting relevant updates for 2.3 version from master
  .github/workflows/CI.yml
  src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourcePermissionServiceImpl.java
  src/core/services-impl/src/main/java/it/geosolutions/geostore/services/TagServiceImpl.java
  src/core/services-impl/src/test/java/it/geosolutions/geostore/services/ResourcePermissionServiceImplTest.java
  src/core/services-impl/src/test/java/it/geosolutions/geostore/services/TagServiceImplTest.java
  src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/UserServiceAuthenticationProvider.java
  src/web/app/src/main/java/it/geosolutions/geostore/init/GeoStoreInit.java
Labels: backport

#423 upgrade spring framework to version 5.3.39
  .github/workflows/CI.yml
  pom.xml
Labels: dependencies

#432 [Backport to 2.3.x][FIXES #426] Support for direct integration on security settings (#429)
  src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/SecurityDAOImpl.java
Labels: backport

#435 [Backport to 2.3.x] Removed editor overwrite at resource permission update (#433).
  src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/SecurityDAOImpl.java
  src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/SecurityDAOTest.java
  src/modules/rest/extjs/src/test/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImplTest.java
  src/web/app/pom.xml
  src/web/app/src/main/java/it/geosolutions/geostore/init/GeoStoreInit.java
Labels: backport

#434 [Backport to 2.3.x] upgrade spring framework to version 5.3.39 (#423)
  .github/workflows/CI.yml
  pom.xml
Labels: backport
